### ISSUE TITLE
Large code process

### ISSUE THREAD

**Issue by dipakbari4** [yahu1031/FlutterBot#35]
Bot needs to read length of code to large-sized post

**Comment by yahu1031** [comment]
@dipakbari4 rephrase it please 😎

**Comment by dipakbari4** [comment]
For preventing user to post bulk lines of code on the chat section and prompt them to use bin sites.

**Comment by yahu1031** [comment]
yeah i wrote that code. may be you can see in some commit. But IDK why i have replaced it with `!code` command 😕
